### ISSUE TITLE
New Workflow! Please read.

### ISSUE THREAD

**Issue by EnumC** [FewdpewGames/unity-game#18]
Hello everyone, To avoid merge conflicts, instead of using " git add \* ", please **only** add and commit the file you have edited. Do not add anything else other than the modified file. 
So for example, if you have edited the file "MainScene.unityproj", do 
" `git add /Assets/Map/MainScene.unityproj` ".

@akhilanganesh @DohyunK @BenCuan @CrispyCookieHD @erwang01

**Comment by 64bitpandas** [comment]
To add on to that, remember to add the .meta file as well. (example:
image.jpg also requires image.jpg.meta)
