### ISSUE TITLE
Unity Mac Support

### ISSUE THREAD

**Issue by aryansidbatte** [FewdpewGames/unity-game#9]
I am not able to open the unity-game folder in my mac. I already enabled windows development support

**Comment by erwang01** [comment]
True same here

----- Reply message -----

**Comment by 64bitpandas** [comment]
Does it work now?

Anyways, do you guys like the new layout?

![image](https://cloud.githubusercontent.com/assets/15005763/12864940/822c7e68-cc52-11e5-9fff-857ab7165f36.png)

**Comment by erwang01** [comment]
It works when I clone from your branch. I have not tried the updated one yet

----- Reply message -----

**Comment by EnumC** [comment]
yups. Looks a lot better!

👍👍👍👍👍

**Comment by 64bitpandas** [comment]
i guess this issue can be closed now.
